INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES
 ('Air Mag', 'Nike', '2016 Air Mag', 15000, 'The Nike MAG is a limited edition shoe created by Nike Inc. It is a replica of a shoe featured in Back to the Future Part II. The Nike Mag was originally released for sale in 2011 and again in 2016. Both launches were extremely limited in quantity.', 2016, 'https://www.flightclub.com/media/catalog/product/cache/1/thumbnail/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/800283_1.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/thumbnail/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/800283_2.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/thumbnail/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/800283_3.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/thumbnail/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/800283_7.jpg');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Cortez', 'Nike', 'Forrest Gump', 80, 'Just like the film, this model Cortez is the same as models released by Nike in the 1970s.', 2017, 'https://stockx-360.imgix.net/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Images/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1545966773&w=1300', 'https://stockx-360.imgix.net/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Images/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Lv2/img32.jpg?auto=format,compress&q=90&updated_at=1545966773&w=1300', 'https://stockx-360.imgix.net/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Images/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Lv2/img24.jpg?auto=format,compress&q=90&updated_at=1545966773&w=1300', 'https://stockx-360.imgix.net/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Images/Nike-Cortez-Basic-Leather-Forrest-Gump-2017/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1545966773&w=1300');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Air Foamposite Pro', 'Nike', 'Color Shift', 230, 'Become a pro at the sneaker game and cop the Air Foamposite Pro Color Shift. This Air Foamposite Pro comes with a dirty rose gold upper, black Nike “Swoosh”, black midsole, and a black sole. These sneakers released in April 2019 and retailed for $230.', 2019, 'https://sneakerbardetroit.com/wp-content/uploads/2019/03/Nike-Air-Foamposite-Pro-Hyper-Crimson-Black-624041-800-Release-Date-4.jpg','https://sneakerbardetroit.com/wp-content/uploads/2019/03/Nike-Air-Foamposite-Pro-Hyper-Crimson-Black-624041-800-Release-Date-2-1.jpg', 'https://sneakerbardetroit.com/wp-content/uploads/2019/03/Nike-Air-Foamposite-Pro-Hyper-Crimson-Black-624041-800-Release-Date-Price-4.jpg', 'https://sneakerbardetroit.com/wp-content/uploads/2019/03/Nike-Air-Foamposite-Pro-Hyper-Crimson-Black-624041-800-Release-Date-Price-5.jpg');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Nike Air Max 270 Doernbecher', 'Nike', 'Black/Metallic Gold-Medium Olive', 150, 'Blend in with the deep pits of the sneaker world while rocking the Air Max 270 Doernbecher (2018). This Air Max 270 comes with an army fatigue upper, gold Nike “Swoosh”, black midsole with gold accents, and a black sole. These sneakers released in December 2018 and retailed for $150.', 2018, 'https://stockx-360.imgix.net/Nike-Air-Max-270-Doernbecher-2018/Images/Nike-Air-Max-270-Doernbecher-2018/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1546756036&w=1300', 'https://stockx-360.imgix.net/Nike-Air-Max-270-Doernbecher-2018/Images/Nike-Air-Max-270-Doernbecher-2018/Lv2/img31.jpg?auto=format,compress&q=90&updated_at=1546756036&w=1300', 'https://stockx-360.imgix.net/Nike-Air-Max-270-Doernbecher-2018/Images/Nike-Air-Max-270-Doernbecher-2018/Lv2/img21.jpg?auto=format,compress&q=90&updated_at=1546756036&w=1300', 'https://stockx-360.imgix.net/Nike-Air-Max-270-Doernbecher-2018/Images/Nike-Air-Max-270-Doernbecher-2018/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1546756036&w=1300');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Nike Epic React Flyknit', 'Nike', 'Wolf-Grey/White-Cool Grey-Pure Platinum', 150, 'Take your everyday training session or casual day to epic new heights in the Women''s Nike Epic React Flyknit Running Shoes.', 2018, 'https://stockx-360.imgix.net/Nike-Epic-React-Flyknit-Wolf-Grey/Images/Nike-Epic-React-Flyknit-Wolf-Grey/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Nike-Epic-React-Flyknit-Wolf-Grey/Images/Nike-Epic-React-Flyknit-Wolf-Grey/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Nike-Epic-React-Flyknit-Wolf-Grey/Images/Nike-Epic-React-Flyknit-Wolf-Grey/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Nike-Epic-React-Flyknit-Wolf-Grey/Images/Nike-Epic-React-Flyknit-Wolf-Grey/Lv2/img08.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Nike Kyrie V Concepts Ikhet', 'Nike', 'Multi-Color', 180, 'This Nike Kyrie 5 is inspired by Kyrie’s Hamsa hand tattoo. Its Sandy Beige upper nods to the age of Ancient Egypt and pyramids, while having a chiseled Grey Swoosh, Red tongue to represent the nose of the Sphinx before it decayed, atop a Purple sole that represents the sunset against the pyramids. Dual branding on the tongue shroud, along with Egyptian hieroglyphs on each heel completes the design.', 2018, 'https://stockx-360.imgix.net/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Images/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1546094117&w=1300', 'https://stockx-360.imgix.net/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Images/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1546094117&w=1300', 'https://stockx-360.imgix.net/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Images/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Lv2/img18.jpg?auto=format,compress&q=90&updated_at=1546094117&w=1300', 'https://stockx-360.imgix.net/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Images/Nike-Kyrie-5-Concepts-Ikhet-Special-Box/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1546094117&w=1300');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Nike Air Max Air Max Day', 'Nike', 'White/Rift Blue-Hyper Jade-Midnight Navy', 150, 'This Nike Kyrie 5 is inspired by Kyrie’s Hamsa hand tattoo. Its Sandy Beige upper nods to the age of Ancient Egypt and pyramids, while having a chiseled Grey Swoosh, Red tongue to represent the nose of the Sphinx before it decayed, atop a Purple sole that represents the sunset against the pyramids. Dual branding on the tongue shroud, along with Egyptian hieroglyphs on each heel completes the design.', 2015, 'https://stockx-360.imgix.net/Nike-Air-Max-Zero-Air-Max-Day_TruView/Images/Nike-Air-Max-Zero-Air-Max-Day_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/Nike-Air-Max-Zero-Air-Max-Day_TruView/Images/Nike-Air-Max-Zero-Air-Max-Day_TruView/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/Nike-Air-Max-Zero-Air-Max-Day_TruView/Images/Nike-Air-Max-Zero-Air-Max-Day_TruView/Lv2/img13.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300', 'https://stockx-360.imgix.net/Nike-Air-Max-Zero-Air-Max-Day_TruView/Images/Nike-Air-Max-Zero-Air-Max-Day_TruView/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1300');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Nike VaporMax Premier Flyknit', 'Nike', 'Black/Metallic Silver-White', 225, 'Nike refers to their VaporMax sole as if you’re walking on clouds. Expanding their VaporMax series, the Swoosh has officially introduced the VaporMax Premier Flyknit. This particular colorway of the shoe comes dressed in a Black, Metallic Silver, White, and Anthracite color scheme. It features a remarkably comfortable design, locked down with a criss-cross leather strap and magnetic closure. Add details includes 3M Reflective hints on its Swoosh logo.', 2018, 'https://stockx-360.imgix.net/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Images/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1546677889&w=1300', 'https://stockx-360.imgix.net/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Images/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Lv2/img29.jpg?auto=format,compress&q=90&updated_at=1546677889&w=1300', 'https://stockx-360.imgix.net/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Images/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1546677889&w=1300', 'https://stockx-360.imgix.net/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Images/Nike-VaporMax-Premier-Flyknit-Black-Metallic-Silver-White/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1546677889&w=1300');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Nike Zoom Pegasus 35 Turbo', 'Nike', 'Barely Grey/Hot Punch-Black', 180, 'The Sneaker either comes with "Zoom" or "Nike Zoom" logo on the sole depending on which region it was sold in. The Nike Zoom Pegasus Turbo Wolf Grey Hot Punch marks one of Nike''s most innovative running shoes to date. Using its brand new Zoom X technology, these shoes will keep your fits fresh and feet cozy all day long. This pair utilizes a translucent upper with a hot punch racing stripe running from the tongue all the way down the laces to the underside of the shoes. These are definitely Lightning McQueen approved. If you are on the market for one of the hottest running shoes of 2018 or just for a fresh pair of kicks, the Nike Zoom Pegasus Turbo is for you. This pair released in July 2018 for $180.', 2018, 'https://stockx-360.imgix.net/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Images/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Images/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Lv2/img26.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Images/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Images/Nike-Zoom-Pegasus-Turbo-Wolf-Grey-Hot-Punch/Lv2/img08.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Shaq Attack', 'Reebok', 'Blue', 160, 'Over 20 years after it originally released, the Reebok Shaq Attaq “Away” in black and Azure Blue returned to stores as a retro in 2013. Originally released in 1992, the Shaq Attaq got its name from Shaquille O’Neal’s ability to attack the rim with avengeance.', 2013, 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/9/9/991769_02.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/9/9/991769_03.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/9/9/991769_04.jpg', 'https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/9/9/991769_01.jpg');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Freestyle HI', 'Reebok', 'White', 75, 'On-trend, in-vogue and all-the-craze. Features a leather upper that is supportive and comfortable. An EVA midsole and terry cloth lining provide lightweight cushioning so you keep moving long after others have stopped.', 2018, 'https://assets.reebok.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/f66b4a0987b34c59bed9a44c0189064c_9366/Freestyle_Hi_White_70_01_standard.jpg', 'https://assets.reebok.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/b5cd3946602c4da5b68da44c018922a2_9366/Freestyle_Hi_White_70_02_standard.jpg', 'https://assets.reebok.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/bfc23e6a20c84f519075a44c018951b5_9366/Freestyle_Hi_White_70_04_standard.jpg', 'https://assets.reebok.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/53283fde763e4ad99f0da44c01896904_9366/Freestyle_Hi_White_70_05_standard.jpg');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Instapump Fury', 'Reebok', 'Grinch', 200, 'Reebok Classics has released their holiday inspired Reebok Insta Pump Fury Grinch edition just in time for Christmas.Inspired by How the Grinch Stole Christmas, this Reebok Insta Pump Fury comes dressed in a Semi Solar Green, Scarlet, Pine Green and Gold color scheme. Featuring a Green faux fur underlays with Red overlays and Metallic Gold branding wrap.', 2016, 'https://stockx-360.imgix.net/Reebok-Instapump-Fury-Grinch/Images/Reebok-Instapump-Fury-Grinch/Lv2/img35.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Reebok-Instapump-Fury-Grinch/Images/Reebok-Instapump-Fury-Grinch/Lv2/img26.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Reebok-Instapump-Fury-Grinch/Images/Reebok-Instapump-Fury-Grinch/Lv2/img22.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Reebok-Instapump-Fury-Grinch/Images/Reebok-Instapump-Fury-Grinch/Lv2/img07.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Classic Nylon', 'Reebok', 'Nipsey Hussle Royal', 125, 'Self-made Los Angeles rap stalwart Nipsey Hussle has joined forces with Reebok for an all-blue Classic Nylon, paying homage to Nipsey’s hometown Dodgers and his oft-referenced neighborhood Crip affiliation. The shoe features an upper composed of nylon and premium suede, while a faint white snakeskin pattern on the heel and Reebok chevron provides just enough contrast. The heel features a great deal of detail as well, with “Rich Rollin” (the name of one of Nipsey’s classic songs) embroidered on the top, and his hometown streets of Crenshaw and Slauson debossed on the bottom. This isn’t the first time Reebok has worked with a famous West Coast rapper on a shoe that draws inspiration from LA’s gang culture either. Before Kendrick Lamar left the brand to join forces with Nike, he also collaborated on a pair of Reebok Classics that aimed to be a call to unity for LA’s Bloods and Crips. The Nipsey Hussle x Reebok Classic Nylon releases this February 17th.', 2018, 'https://stockx-360.imgix.net/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Images/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Lv2/img36.jpg?auto=format,compress&q=90&updated_at=1549070530&w=2200', 'https://stockx-360.imgix.net/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Images/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Lv2/img29.jpg?auto=format,compress&q=90&updated_at=1549070530&w=2200', 'https://stockx-360.imgix.net/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Images/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Lv2/img22.jpg?auto=format,compress&q=90&updated_at=1549070530&w=2200', 'https://stockx-360.imgix.net/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Images/Reebok-Classic-Nylon-Nipsey-Hussle-Royal/Lv2/img08.jpg?auto=format,compress&q=90&updated_at=1549070530&w=2200');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Classic Nylon', 'Reebok', 'Big Shaqtus', 160, 'The Reebok Shaq Attaq “Big Shaqtus” retro pays homage to Shaquille O’Neal’s days in the desert as a member of the Phoenix Suns. Although Shaq’s era in Phoenix was short-lived, in the year he was there Phoenix hosted the NBA All Star Game and Shaquille O’Neal was voted on to the Western Conference team for his 15th All Star appearance and named co-MVP alongside his former teammate Kobe Bryant. The Big Shaqtus Shaq Attaq was initially nicknamed “Suns” by sneaker blogs due to the obvious Phoenix inspired color combination of black, purple and orange. The Shaq Attaq originally released in 1992 as Shaquille O’Neal’s first signature sneaker. At the time, it debuted Shaq’s personal Dunkman logo on the heel and featured the first Graphlite shank plate ever used on a Reebok basketball shoe. In 2013, the Shaq Attaq returned as a retro for the very first time. A number of colorways released, including new makeups, the classic home and away original color makeups, and of course, the Phoenix Suns inspired “Big Shaqtus” version. Since Shaq is no stranger to nicknames--Diesel, Big Man, Big Shamrock, Big Aristotle, Shaq Daddy, just to name a few--the Reebok Shaq Attaq “Big Shaqtus” uses one of his many to tie the colorway together with O’Neal and his history making career.', 2013, 'https://stockx.imgix.net/Reebok-Shaq-Attaq-Big-Shaqtus.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1538080256&w=2200', 'http://3app.kicksonfire.com/kofapp/upload/events_images/iphone_f7d377f3057a4d017f68775b7f7084265222e4bae600a.jpg', 'http://3app.kicksonfire.com/kofapp/upload/events_images/iphone_100c7ff033f5b766abde86c5fe26517f5222e4bb3c42f.jpg', 'http://3app.kicksonfire.com/kofapp/upload/events_images/iphone_f7d377f3057a4d017f68775b7f7084265222e4ba9e794.jpg');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Alien Stomper Mid Final Scene Pack', 'Reebok', 'Retro Yellow/Black-Gum', 325, 'The Reebok Alien Stomper Mid returned for another special release in 2017. Known as the "Final Scene" Pack, this two-shoe collection features two colorways of the futuristic Alien Stomper inspired by iconic elements from the final battle of the 1986 film, Aliens. Nicknamed the "Power Loader" and "Queen Alien" editions respectively, both pairs come in a special double box with parts of the original script engrained in it. The "Power Loader" edition, which draws inspiration from the machine Ellen Ripley used to defeat her enemy comes in a retro yellow and black colorway. Sporting a yellow-based upper with black accents, a full gum outsole and detailing tying back to the movie. The "Queen Alien" edition comes in all-black. Featuring a full patent leather upper with glow-in-the-dark hits and movie detailing. The Reebok Alien Stomper Mid "Final Scene" Pack was released on July 18th, 2017 retailing for $325. This pack should appease both fans of the sneaker as well as the Aliens film franchise. If you were lucky enough to snag a set, hit up the marketplace to see what they are going for. If you''re on the hunt for one, you can buy these Reebok''s online as we have people looking to sell them today.', 2017, 'https://stockx-360.imgix.net/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Images/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1546757226&w=2200', 'https://stockx-360.imgix.net/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Images/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Lv2/img29.jpg?auto=format,compress&q=90&updated_at=1546757226&w=2200', 'https://stockx-360.imgix.net/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Images/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Lv2/img23.jpg?auto=format,compress&q=90&updated_at=1546757226&w=2200', 'https://stockx-360.imgix.net/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Images/Reebok-Alien-Stomper-Mid-Final-Scene-Pack/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1546757226&w=2200');

INSERT INTO shoes(name, brand, colorway, price, description, year_released, image_1_url, image_2_url, image_3_url, image_4_url)
VALUES('Blaze of Glory Ronnie Fieg x Highsnobiety A Tale of Two Cities', 'Puma', 'Dark Navy', 160, 'The Blaze of Glory takes on a patriotic theme in navy, red and white, adjoined with a quilted upper and co-branding at the forefoot strap. Asymmetrical stars and strips in a debossed finish close the look along with a speckled Trinomic midsole.', 2015, 'https://stockx-360.imgix.net/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Images/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Images/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Images/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Lv2/img12.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200', 'https://stockx-360.imgix.net/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Images/Puma-Blaze-Of-Glory-Ronnie-Fieg-Two-Cities_TruView/Lv2/img06.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200');

